python query.py 四季
python query.py 少年
python query.py 衣衫
python query.py 眉目
python query.py 无穷
python query.py 落款
python query.py 生死
python query.py 春秋
python query.py 红尘
python query.py 桃花
python query.py 朱砂
python query.py 相思
python query.py 流年
python query.py 回眸
python query.py 江南
python query.py 长安
python query.py 杨柳
python query.py 江湖
python query.py 风雨